import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  bookSidebar: [
    {
      type: 'category',
      label: 'Module 1: Introduction to Physical AI',
      items: [
        'module-1/chapter-1-1',
        'module-1/chapter-1-2',
        'module-1/chapter-1-3',
        'module-1/chapter-1-4',
        'module-1/chapter-1-5',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Humanoid Robot Kinematics',
      items: [
        'module-2/chapter-2-1',
        'module-2/chapter-2-2',
        'module-2/chapter-2-3',
        'module-2/chapter-2-4',
        'module-2/chapter-2-5',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: Dynamics and Control',
      items: [
        'module-3/chapter-3-1',
        'module-3/chapter-3-2',
        'module-3/chapter-3-3',
        'module-3/chapter-3-4',
        'module-3/chapter-3-5',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Sensing and Perception',
      items: [
        'module-4/chapter-4-1',
        'module-4/chapter-4-2',
        'module-4/chapter-4-3',
        'module-4/chapter-4-4',
        'module-4/chapter-4-5',
      ],
    },
    {
      type: 'category',
      label: 'Module 5: Advanced Topics and Future Trends',
      items: [
        'module-5/chapter-5-1',
        'module-5/chapter-5-2',
        'module-5/chapter-5-3',
        'module-5/chapter-5-4',
        'module-5/chapter-5-5',
      ],
    },
  ],
};

export default sidebars;
