openapi: 3.0.0
info:
  title: Authentication and User Management API
  version: 1.0.0
paths:
  /auth/signup:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - background
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: secure_password
                background:
                  type: string
                  description: User's background (e.g., student, professional)
                  example: student
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User created successfully
                  user_id:
                    type: string
                    format: uuid
        '400':
          description: Bad Request (e.g., email already registered)
        '500':
          description: Internal Server Error

  /auth/signin:
    post:
      summary: Authenticate and sign in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: secure_password
      responses:
        '200':
          description: User successfully signed in
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  token_type:
                    type: string
                    example: bearer
        '401':
          description: Unauthorized (e.g., invalid credentials)
        '500':
          description: Internal Server Error

  /users/me:
    get:
      summary: Get current user's profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Current user profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized
        '404':
          description: User not found
        '500':
          description: Internal Server Error
    put:
      summary: Update current user's profile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProfileUpdate'
      responses:
        '200':
          description: User profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Bad Request (e.g., invalid input)
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    UserProfile:
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          readOnly: true
        auth_provider_id:
          type: string
          readOnly: true
        full_name:
          type: string
          nullable: true
        email:
          type: string
          format: email
          readOnly: true
        registration_date:
          type: string
          format: date-time
          readOnly: true
        last_login_date:
          type: string
          format: date-time
          readOnly: true
        profile_data:
          type: object
          properties:
            background_sw:
              type: string
            background_hw:
              type: string
            preferences:
              type: object
              additionalProperties: true
    UserProfileUpdate:
      type: object
      properties:
        full_name:
          type: string
          nullable: true
        profile_data:
          type: object
          properties:
            background_sw:
              type: string
            background_hw:
              type: string
            preferences:
              type: object
              additionalProperties: true