openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
  description: API for user authentication via Auth0.
servers:
  - url: /api/v1
paths:
  /auth/signup:
    post:
      summary: Register a new user
      operationId: signupUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - background_sw
                - background_hw
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's chosen password
                background_sw:
                  type: string
                  description: User's software background (e.g., "Student", "Professional")
                background_hw:
                  type: string
                  description: User's hardware background (e.g., "Student", "Professional")
      responses:
        '200':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    format: uuid
                  message:
                    type: string
        '400':
          description: Invalid input or email already registered
  /auth/signin:
    post:
      summary: Authenticate an existing user
      operationId: signinUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  description: User's password
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT access token
                  token_type:
                    type: string
                    example: bearer
        '401':
          description: Invalid credentials
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
