openapi: 3.0.0
info:
  title: User Profile API
  version: 1.0.0
  description: API for managing user profiles.
servers:
  - url: /api/v1
paths:
  /users/me:
    get:
      summary: Get authenticated user's profile
      operationId: getUserProfile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  background_sw:
                    type: string
                  background_hw:
                    type: string
                  preferences:
                    type: object
                    properties:
                      translation_language:
                        type: string
                        enum: [ "en", "ur" ]
                        default: "en"
                      chapter_order:
                        type: array
                        items:
                          type: string
                      hidden_chapters:
                        type: array
                        items:
                          type: string
                      highlighted_chapters:
                        type: array
                        items:
                          type: string
        '401':
          description: Unauthorized
    put:
      summary: Update authenticated user's profile
      operationId: updateUserProfile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                background_sw:
                  type: string
                  description: User's software background (e.g., "Student", "Professional")
                background_hw:
                  type: string
                  description: User's hardware background (e.g., "Student", "Professional")
                preferences:
                  type: object
                  properties:
                    translation_language:
                      type: string
                      enum: [ "en", "ur" ]
                      default: "en"
                    chapter_order:
                      type: array
                      items:
                        type: string
                    hidden_chapters:
                      type: array
                      items:
                        type: string
                    highlighted_chapters:
                      type: array
                      items:
                        type: string
      responses:
        '200':
          description: User profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    format: uuid
                  message:
                    type: string
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT